[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = {path = "../../lib/shared" }
serde = { version = "1", features = ["serde_derive"]}
serde_json = "1"
md5 = "0.7.0"